name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: Simple JS Action
        id: greet # step id/key(optional)
        uses: actions/hello-world-javascript-action@v1 # using actions, github_user/name_of_action 
        with: 
          who-to-greet: Divino # passing inputs to action
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"