name: Functions

on: [push, pull_request]

jobs: 
  functions:
    name: Functions job
    runs-on: ubuntu-latest
    steps:
      - name: dump
        continue-on-error: true
        timeout-minutes: 360
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ startsWith('hello', 'he') }}
          echo ${{ endsWith('hello', 'llo') }}
          echo ${{ format('hello {0} {1} {2}', 'world', 'my', 'friend') }}

  functions-with-env:
    name: Functions with env variables
    runs-on: ubuntu-latest
    steps:
      - name: 'Showing github context'
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  
  functions-with-expression:
    name: This job will run only in push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: This step will failure
        run: eccho Hello

      - name: This step will run if the previous one fails´
        if: failure()
        run: echo 'the previous job fails'

      - name: This step will always run
        if: always()
        run: echo 'Always running'

      - name: This step will run only if the workflow was cancelled.
        if: cancelled()
        run: echo 'Was cancelled'