name: Shell Commands

on: [push] #push, pull request, issue, schedule, external event

jobs: 
  #job name
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v 